// frontend-react/src/components/ManageRoles.tsx
import React, { useEffect, useState } from 'react';
import { userService } from '../services/userService';
import { roleService } from '../services/roleService';
import type { User, Role } from '../types';
import './ManageRoles.css';

const ManageRoles: React.FC = () => {
	const [users, setUsers] = useState<User[]>([]);
	const [roles, setRoles] = useState<Role[]>([]);
	const [selectedUser, setSelectedUser] = useState<User | null>(null);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState('');

	useEffect(() => {
		loadData();
	}, []);

	const loadData = async () => {
		try {
			setLoading(true);
			const [usersData, rolesData] = await Promise.all([userService.getAllUsers(), roleService.getAllRoles()]);
			setUsers(usersData);
			setRoles(rolesData);
			setError('');
		} catch (err: unknown) {
			setError('Failed to load data');
			console.error('Failed to load data:', err);
		} finally {
			setLoading(false);
		}
	};

	const toggleRole = async (roleId: number) => {
		if (!selectedUser) return;

		const hasRole = selectedUser.roles.some((r) => r.id === roleId);

		try {
			if (hasRole) {
				await roleService.removeRole({ userId: selectedUser.id, roleId });
			} else {
				await roleService.assignRole({ userId: selectedUser.id, roleId });
			}

			// Reload data after successful toggle
			await loadData();

			// Update selected user with new data
			const updatedUser = users.find((u) => u.id === selectedUser.id);
			if (updatedUser) {
				setSelectedUser(updatedUser);
			}
		} catch (err: unknown) {
			if (err && typeof err === 'object' && 'response' in err) {
				const axiosError = err as { response?: { data?: { message?: string } } };
				alert(axiosError.response?.data?.message || 'Failed to toggle role');
			} else {
				alert('Failed to toggle role');
			}
		}
	};

	const hasRole = (roleId: number): boolean => {
		if (!selectedUser) return false;
		return selectedUser.roles.some((r) => r.id === roleId);
	};

	if (loading) {
		return <div className='loading'>Loading...</div>;
	}

	if (error) {
		return <div className='error'>{error}</div>;
	}

	return (
		<div className='manage-roles-container'>
			<h2>Manage User Roles</h2>

			<div className='roles-layout'>
				<div className='users-panel'>
					<h3>Users</h3>
					<div className='users-list'>
						{users.map((user) => (
							<div
								key={user.id}
								className={`user-item ${selectedUser?.id === user.id ? 'selected' : ''}`}
								onClick={() => setSelectedUser(user)}
							>
								<div>
									<strong>{user.email}</strong>
									<div className='user-roles'>
										{user.roles.map((role) => (
											<span
												key={role.id}
												className='role-badge'
											>
												{role.name}
											</span>
										))}
									</div>
								</div>
							</div>
						))}
					</div>
				</div>

				<div className='roles-panel'>
					{selectedUser ? (
						<>
							<h3>Roles for {selectedUser.email}</h3>
							<div className='roles-grid'>
								{roles.map((role) => (
									<div
										key={role.id}
										className='role-card'
									>
										<div className='role-info'>
											<strong>{role.name}</strong>
											<span className={hasRole(role.id) ? 'assigned' : 'not-assigned'}>
												{hasRole(role.id) ? '✓ Assigned' : '✗ Not Assigned'}
											</span>
										</div>
										<button
											onClick={() => toggleRole(role.id)}
											className={hasRole(role.id) ? 'remove-btn' : 'assign-btn'}
										>
											{hasRole(role.id) ? 'Remove' : 'Assign'}
										</button>
									</div>
								))}
							</div>
						</>
					) : (
						<div className='select-user-message'>
							<p>Select a user to manage their roles</p>
						</div>
					)}
				</div>
			</div>
		</div>
	);
};

export default ManageRoles;

// frontend/src/app/components/manage-roles/manage-roles.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UserService, User } from '../../services/user.service';
import { RoleService, Role } from '../../services/role.service';

@Component({
  selector: 'app-manage-roles',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './manage-roles.component.html',
  styleUrls: ['./manage-roles.component.css'],
})
export class ManageRolesComponent implements OnInit {
  private userService = inject(UserService);
  private roleService = inject(RoleService);

  users: User[] = [];
  roles: Role[] = [];
  selectedUser: User | null = null;
  loading = false;
  error: string | null = null;
  success: string | null = null;

  ngOnInit() {
    this.loadData();
  }

  loadData() {
    this.loading = true;
    this.error = null;

    // Load users and roles in parallel
    Promise.all([
      this.userService.getAllUsers().toPromise(),
      this.roleService.getAllRoles().toPromise(),
    ])
      .then(([users, roles]) => {
        this.users = users || [];
        this.roles = roles || [];
        this.loading = false;
      })
      .catch((err) => {
        console.error('Failed to load data:', err);
        this.error = 'Failed to load users and roles. Please try again.';
        this.loading = false;
      });
  }

  selectUser(user: User) {
    this.selectedUser = user;
    this.error = null;
    this.success = null;
  }

  hasRole(roleId: number): boolean {
    if (!this.selectedUser) return false;
    return this.selectedUser.roles.some((role) => role.id === roleId);
  }

  toggleRole(roleId: number) {
    if (!this.selectedUser) return;

    this.error = null;
    this.success = null;

    const hasRole = this.hasRole(roleId);
    const action = hasRole ? 'remove' : 'assign';
    const roleName = this.roles.find((r) => r.id === roleId)?.name || 'Unknown';

    const request = {
      userId: this.selectedUser.id,
      roleId: roleId,
    };

    const observable = hasRole
      ? this.roleService.removeRole(request)
      : this.roleService.assignRole(request);

    observable.subscribe({
      next: () => {
        this.success = `Successfully ${
          action === 'assign' ? 'assigned' : 'removed'
        } role "${roleName}"`;

        // Update local state
        if (this.selectedUser) {
          if (action === 'assign') {
            const role = this.roles.find((r) => r.id === roleId);
            if (role && !this.selectedUser.roles.some((r) => r.id === roleId)) {
              this.selectedUser.roles.push(role);
            }
          } else {
            this.selectedUser.roles = this.selectedUser.roles.filter(
              (r) => r.id !== roleId,
            );
          }

          // Update user in the list
          const userIndex = this.users.findIndex(
            (u) => u.id === this.selectedUser!.id,
          );
          if (userIndex !== -1) {
            this.users[userIndex] = { ...this.selectedUser };
          }
        }

        // Clear success message after 3 seconds
        setTimeout(() => {
          this.success = null;
        }, 3000);
      },
      error: (err) => {
        console.error(`Failed to ${action} role:`, err);
        this.error =
          err.error?.message || `Failed to ${action} role. Please try again.`;
      },
    });
  }

  getRoleNames(user: User): string {
    return user.roles.map((role) => role.name).join(', ') || 'No roles';
  }
}

<div class="manage-roles-container">
  <h2>Manage User Roles</h2>

  <div *ngIf="loading" class="loading">Loading users and roles...</div>

  <div *ngIf="error" class="error">{{ error }}</div>
  <div *ngIf="success" class="success">{{ success }}</div>

  <div class="roles-manager" *ngIf="!loading">
    <!-- User List -->
    <div class="user-list-section">
      <h3>Select User</h3>

      <div *ngIf="users.length === 0" class="empty">
        No users found in the system.
      </div>

      <div class="user-list" *ngIf="users.length > 0">
        <div
          class="user-item"
          *ngFor="let user of users"
          [class.selected]="selectedUser?.id === user.id"
          (click)="selectUser(user)"
        >
          <div class="user-info">
            <strong>{{ user.email }}</strong>
            <span class="user-name" *ngIf="user.firstName || user.lastName">
              {{ user.firstName }} {{ user.lastName }}
            </span>
            <span class="user-roles">{{ getRoleNames(user) }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Role Assignment -->
    <div class="role-assignment-section">
      <h3>Assign/Remove Roles</h3>

      <div *ngIf="!selectedUser" class="empty">
        Select a user from the left to manage their roles.
      </div>

      <div *ngIf="selectedUser" class="role-assignment">
        <div class="selected-user-info">
          <h4>{{ selectedUser.email }}</h4>
          <p *ngIf="selectedUser.firstName || selectedUser.lastName">
            {{ selectedUser.firstName }} {{ selectedUser.lastName }}
          </p>
        </div>

        <div class="roles-grid">
          <div
            class="role-card"
            *ngFor="let role of roles"
            [class.active]="hasRole(role.id)"
          >
            <div class="role-info">
              <strong>{{ role.name }}</strong>
            </div>
            <button
              class="btn-toggle"
              [class.assigned]="hasRole(role.id)"
              (click)="toggleRole(role.id)"
            >
              {{ hasRole(role.id) ? 'Remove' : 'Assign' }}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
