// frontend/src/app/components/product-list/product-list.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ProductService, Product } from '../../services/product.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-product-list',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css'],
})
export class ProductListComponent implements OnInit {
  private productService = inject(ProductService);
  private authService = inject(AuthService);

  products: Product[] = [];
  loading = false;
  error: string | null = null;
  currentPage = 1;
  totalPages = 1;
  isAuthenticated$ = this.authService.isAuthenticated$;

  ngOnInit() {
    this.loadProducts();
  }

  loadProducts(page: number = 1) {
    this.loading = true;
    this.error = null;

    this.productService.getProducts(page, 10).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.products = response.data.data;
          this.currentPage = response.data.meta.page;
          this.totalPages = response.data.meta.totalPages;
        }
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load products. Please try again later.';
        console.error('Product load error:', err);
        this.loading = false;
      },
    });
  }

  loadPage(page: number) {
    if (page >= 1 && page <= this.totalPages) {
      this.loadProducts(page);
    }
  }

  addToOrder(product: Product) {
    // Navigate to order page with product pre-selected
    console.log('Add to order:', product);
    // This would be implemented with a shopping cart service in production
    alert(`Product "${product.title}" added to order (feature coming soon)`);
  }
}

<div class="product-list-container">
  <div class="header">
    <h2>Available Products</h2>
    <button
      class="btn-create"
      (click)="navigateToCreate()"
      *ngIf="canToggleStatus()"
    >
      + Create Product
    </button>
  </div>

  <div *ngIf="loading" class="loading">Loading products...</div>

  <div *ngIf="error" class="error">{{ error }}</div>

  <div *ngIf="!loading && products.length === 0" class="empty">
    <p>No products available at the moment.</p>
    <p class="hint">
      Run the seeder to populate products: <code>npm run seed:run</code>
    </p>
  </div>

  <div class="products-grid" *ngIf="products.length > 0">
    <div
      class="product-card"
      *ngFor="let product of products"
      [class.inactive]="!product.isActive"
    >
      <div class="product-header">
        <h3>{{ product.title }}</h3>
        <span class="product-code">{{ product.code }}</span>
        <button
          class="status-badge"
          [class.active]="product.isActive"
          [class.inactive-badge]="!product.isActive"
          [class.clickable]="canToggleStatus()"
          [disabled]="!canToggleStatus()"
          (click)="toggleProductStatus(product, $event)"
          [title]="
            canToggleStatus()
              ? 'Click to ' + (product.isActive ? 'deactivate' : 'activate')
              : 'You need Admin or Merchant role'
          "
        >
          {{ product.isActive ? 'Active' : 'Inactive' }}
        </button>
      </div>
      <p class="product-description">
        {{ product.description || 'No description available' }}
      </p>
      <div class="product-footer">
        <span class="variation-type">{{ product.variationType }}</span>
        <button
          class="btn-order"
          (click)="addToOrder(product)"
          [disabled]="!(isAuthenticated$ | async)"
        >
          {{ (isAuthenticated$ | async) ? 'Add to Order' : 'Login to Order' }}
        </button>
      </div>
    </div>
  </div>

  <div class="pagination" *ngIf="totalPages > 1">
    <button
      (click)="loadPage(currentPage - 1)"
      [disabled]="currentPage === 1"
      class="btn-pagination"
    >
      Previous
    </button>
    <span class="page-info">Page {{ currentPage }} of {{ totalPages }}</span>
    <button
      (click)="loadPage(currentPage + 1)"
      [disabled]="currentPage === totalPages"
      class="btn-pagination"
    >
      Next
    </button>
  </div>
</div>

// frontend-react/src/components/ProductList.tsx
import React, { useEffect, useState } from 'react';
import { productService } from '../services/productService';
import type { Product } from '../types';
import './ProductList.css';

const ProductList: React.FC = () => {
	const [products, setProducts] = useState<Product[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState('');

	useEffect(() => {
		loadProducts();
	}, []);

	const loadProducts = async () => {
		try {
			setLoading(true);
			const response = await productService.getProducts(1, 100);

			// Sort products: active first, inactive last
			const sortedProducts = response.data.data.sort((a, b) => Number(b.isActive) - Number(a.isActive));

			setProducts(sortedProducts);
			setError('');
		} catch (err: unknown) {
			console.error('Product load error:', err);
			setError('Failed to load products');
		} finally {
			setLoading(false);
		}
	};

	const handleToggleStatus = async (productId: number) => {
		try {
			await productService.toggleProductStatus(productId);
			loadProducts(); // Reload products after toggle
		} catch (err: unknown) {
			console.error('Toggle status error:', err);
			alert('Failed to toggle product status');
		}
	};

	if (loading) {
		return <div className='loading'>Loading products...</div>;
	}

	if (error) {
		return <div className='error'>{error}</div>;
	}

	return (
		<div className='product-list-container'>
			<h2>Product List</h2>

			{products.length === 0 ? (
				<p className='no-products'>No products found</p>
			) : (
				<div className='product-grid'>
					{products.map((product) => (
						<div
							key={product.id}
							className={`product-card ${!product.isActive ? 'inactive' : ''}`}
						>
							<div className='product-header'>
								<h3>{product.title || 'Untitled Product'}</h3>
								<span className={`status-badge ${product.isActive ? 'active' : 'inactive'}`}>
									{product.isActive ? 'Active' : 'Inactive'}
								</span>
							</div>

							<div className='product-info'>
								<p>
									<strong>Code:</strong> {product.code}
								</p>
								<p>
									<strong>Description:</strong> {product.description || 'No description'}
								</p>
								<p>
									<strong>Variation:</strong> {product.variationType || 'N/A'}
								</p>
							</div>

							<button
								onClick={() => handleToggleStatus(product.id)}
								className='toggle-button'
							>
								{product.isActive ? 'Deactivate' : 'Activate'}
							</button>
						</div>
					))}
				</div>
			)}
		</div>
	);
};

export default ProductList;
