// frontend-react/src/components/Navbar.tsx
import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import './Navbar.css';

const Navbar: React.FC = () => {
	const { user, isAuthenticated, logout, isAdmin } = useAuth();
	const navigate = useNavigate();

	const handleLogout = () => {
		logout();
		navigate('/login');
	};

	if (!isAuthenticated) {
		return null;
	}

	return (
		<nav className='navbar'>
			<div className='navbar-brand'>
				<Link to='/products'>E-Commerce</Link>
			</div>

			<ul className='navbar-menu'>
				<li>
					<Link to='/products'>Products</Link>
				</li>
				<li>
					<Link to='/create-product'>Create Product</Link>
				</li>
				<li>
					<Link to='/create-order'>Create Order</Link>
				</li>
				<li>
					<Link to='/orders'>My Orders</Link>
				</li>
				{isAdmin() && (
					<li>
						<Link to='/manage-roles'>Manage Roles</Link>
					</li>
				)}
			</ul>

			<div className='navbar-user'>
				<span className='user-email'>{user?.email}</span>
				<button
					onClick={handleLogout}
					className='logout-button'
				>
					Logout
				</button>
			</div>
		</nav>
	);
};

export default Navbar;

// frontend/src/app/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  isAuthenticated$ = this.authService.isAuthenticated$;

  logout() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<nav class="navbar">
  <div class="nav-container">
    <a routerLink="/" class="nav-brand">E-Commerce</a>

    <div class="nav-links">
      <a routerLink="/products" routerLinkActive="active">Products</a>

      <ng-container *ngIf="isAuthenticated$ | async">
        <a routerLink="/create-order" routerLinkActive="active">Create Order</a>
        <a routerLink="/orders" routerLinkActive="active">My Orders</a>
        <a
          *ngIf="isAdmin()"
          routerLink="/manage-roles"
          routerLinkActive="active"
        >
          Manage Roles
        </a>
        <button class="btn-logout" (click)="logout()">Logout</button>
      </ng-container>

      <a
        *ngIf="!(isAuthenticated$ | async)"
        routerLink="/login"
        routerLinkActive="active"
      >
        Login
      </a>
    </div>
  </div>
</nav>
