// frontend/src/app/components/create-order/create-order.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { OrderService, CreateOrder } from '../../services/order.service';
import { ProductService, Product } from '../../services/product.service';

interface OrderItem {
  product: Product;
  quantity: number;
}

@Component({
  selector: 'app-create-order',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './create-order.component.html',
  styleUrls: ['./create-order.component.css'],
})
export class CreateOrderComponent implements OnInit {
  private orderService = inject(OrderService);
  private productService = inject(ProductService);
  private router = inject(Router);

  availableProducts: Product[] = [];
  orderItems: OrderItem[] = [];
  loadingProducts = false;
  submitting = false;
  error: string | null = null;
  success = false;

  ngOnInit() {
    this.loadProducts();
  }

  loadProducts() {
    this.loadingProducts = true;
    this.productService.getProducts(1, 100).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          // Sort products: active first, inactive last
          this.availableProducts = response.data.data.sort(
            (a, b) => Number(b.isActive) - Number(a.isActive),
          );
        }
        this.loadingProducts = false;
      },
      error: (err) => {
        console.error('Failed to load products:', err);
        this.loadingProducts = false;
      },
    });
  }

  addProduct(product: Product) {
    // Prevent adding inactive products
    if (!product.isActive) {
      console.warn('Cannot add inactive product:', product.title);
      return;
    }

    const existing = this.orderItems.find(
      (item) => item.product.id === product.id,
    );
    if (existing) {
      existing.quantity++;
    } else {
      this.orderItems.push({ product, quantity: 1 });
    }
  }

  removeItem(index: number) {
    this.orderItems.splice(index, 1);
  }

  increaseQuantity(index: number) {
    this.orderItems[index].quantity++;
  }

  decreaseQuantity(index: number) {
    if (this.orderItems[index].quantity > 1) {
      this.orderItems[index].quantity--;
    }
  }

  submitOrder() {
    this.submitting = true;
    this.error = null;

    const order: CreateOrder = {
      items: this.orderItems.map((item) => ({
        productId: item.product.id,
        quantity: item.quantity,
      })),
    };

    this.orderService.createOrder(order).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.success = true;
          setTimeout(() => {
            this.router.navigate(['/orders']);
          }, 2000);
        }
        this.submitting = false;
      },
      error: (err) => {
        this.error = 'Failed to place order. Please try again.';
        console.error('Order submission error:', err);
        this.submitting = false;
      },
    });
  }
}

<div class="order-container">
  <h2>Create Order</h2>

  <div class="order-builder">
    <div class="product-selector">
      <h3>Select Products</h3>

      <div *ngIf="loadingProducts" class="loading">Loading products...</div>

      <div
        *ngIf="!loadingProducts && availableProducts.length === 0"
        class="empty"
      >
        No active products available. Run the seeder to populate products.
      </div>

      <div class="product-list" *ngIf="availableProducts.length > 0">
        <div
          class="product-item"
          [class.inactive]="!product.isActive"
          *ngFor="let product of availableProducts"
        >
          <div class="product-info">
            <strong>{{ product.title }}</strong>
            <span class="product-code">{{ product.code }}</span>
            <span class="status-badge inactive" *ngIf="!product.isActive">
              Inactive
            </span>
          </div>
          <button
            class="btn-add"
            (click)="addProduct(product)"
            [disabled]="!product.isActive"
            [title]="
              !product.isActive
                ? 'This product is inactive and cannot be added to orders'
                : 'Add to order'
            "
          >
            {{ product.isActive ? 'Add to Order' : 'Unavailable' }}
          </button>
        </div>
      </div>
    </div>

    <div class="order-summary">
      <h3>Order Items</h3>

      <div *ngIf="orderItems.length === 0" class="empty">
        No items in order. Add products from the left.
      </div>

      <div class="order-items" *ngIf="orderItems.length > 0">
        <div class="order-item" *ngFor="let item of orderItems; let i = index">
          <div class="item-details">
            <strong>{{ item.product.title }}</strong>
            <div class="quantity-control">
              <button (click)="decreaseQuantity(i)" class="btn-qty">-</button>
              <input
                type="number"
                [(ngModel)]="item.quantity"
                min="1"
                class="qty-input"
              />
              <button (click)="increaseQuantity(i)" class="btn-qty">+</button>
            </div>
          </div>
          <button class="btn-remove" (click)="removeItem(i)">Remove</button>
        </div>
      </div>

      <div class="order-actions" *ngIf="orderItems.length > 0">
        <button
          class="btn-submit"
          (click)="submitOrder()"
          [disabled]="submitting"
        >
          {{ submitting ? 'Placing Order...' : 'Place Order' }}
        </button>
      </div>

      <div *ngIf="error" class="error">{{ error }}</div>
      <div *ngIf="success" class="success">
        Order placed successfully! Redirecting...
      </div>
    </div>
  </div>
</div>

// frontend-react/src/components/CreateOrder/CreateOrder.tsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { productService } from '../../services/productService';
import { orderService } from '../../services/orderService';
import { useSocket } from '../../hooks/useSocket';
import type { Product, CreateOrderItem } from '../../types';
import './CreateOrder.css';

type OrderStatus = 'idle' | 'creating' | 'processing' | 'confirmed' | 'failed';

const CreateOrder: React.FC = () => {
	const [products, setProducts] = useState<Product[]>([]);
	const [orderItems, setOrderItems] = useState<CreateOrderItem[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState('');
	const [orderStatus, setOrderStatus] = useState<OrderStatus>('idle');
	const [currentOrderId, setCurrentOrderId] = useState<number | null>(null);

	const navigate = useNavigate();
	const { socket, isConnected } = useSocket();

	useEffect(() => {
		loadProducts();
	}, []);

	// Listen for WebSocket order updates
	useEffect(() => {
		if (!socket || !isConnected) return;

		const handleOrderUpdate = (data: { orderId: number; status: string; message?: string }) => {
			console.log('📦 Order update received:', data);

			// Only process updates for the current order
			if (currentOrderId && data.orderId === currentOrderId) {
				const status = data.status.toUpperCase();

				if (status === 'PROCESSING') {
					setOrderStatus('processing');
				} else if (status === 'CONFIRMED') {
					setOrderStatus('confirmed');
					// Navigate to orders page after a short delay
					setTimeout(() => {
						navigate('/orders');
					}, 2000);
				} else if (status === 'FAILED') {
					setOrderStatus('failed');
					alert(data.message || 'Order processing failed');
					// Reset after showing error
					setTimeout(() => {
						setOrderStatus('idle');
						setCurrentOrderId(null);
					}, 3000);
				}
			}
		};

		socket.on('order-update', handleOrderUpdate);

		return () => {
			socket.off('order-update', handleOrderUpdate);
		};
	}, [socket, isConnected, currentOrderId, navigate]);

	const loadProducts = async () => {
		try {
			setLoading(true);
			const response = await productService.getProducts(1, 100);

			// Sort products: active first, inactive last
			const sortedProducts = response.data.data.sort((a, b) => Number(b.isActive) - Number(a.isActive));

			setProducts(sortedProducts);
			setError('');
		} catch (err: unknown) {
			console.error('Failed to load products:', err);
			setError('Failed to load products');
		} finally {
			setLoading(false);
		}
	};

	const addProduct = (product: Product) => {
		if (!product.isActive) {
			alert('Cannot add inactive product to order');
			return;
		}

		const existingItem = orderItems.find((item) => item.productId === product.id);

		if (existingItem) {
			setOrderItems(
				orderItems.map((item) => (item.productId === product.id ? { ...item, quantity: item.quantity + 1 } : item)),
			);
		} else {
			setOrderItems([...orderItems, { productId: product.id, quantity: 1 }]);
		}
	};

	const updateQuantity = (productId: number, quantity: number) => {
		if (quantity < 1) {
			removeProduct(productId);
			return;
		}

		setOrderItems(orderItems.map((item) => (item.productId === productId ? { ...item, quantity } : item)));
	};

	const removeProduct = (productId: number) => {
		setOrderItems(orderItems.filter((item) => item.productId !== productId));
	};

	const handleCreateOrder = async () => {
		if (orderItems.length === 0) {
			alert('Please add at least one product to the order');
			return;
		}

		try {
			setOrderStatus('creating');
			const response = await orderService.createOrder({ items: orderItems });

			if (response.isSuccess && response.data) {
				// Order created successfully, now waiting for async processing
				setCurrentOrderId(response.data.id);
				// Status will be updated via WebSocket
				console.log('✅ Order created, waiting for processing updates...');
			}
		} catch (err: unknown) {
			setOrderStatus('failed');
			if (err && typeof err === 'object' && 'response' in err) {
				const axiosError = err as { response?: { data?: { message?: string } } };
				alert(axiosError.response?.data?.message || 'Failed to create order');
			} else {
				alert('Failed to create order');
			}
			// Reset status after error
			setTimeout(() => {
				setOrderStatus('idle');
			}, 2000);
		}
	};

	if (loading) {
		return <div className='loading'>Loading products...</div>;
	}

	if (error) {
		return <div className='error'>{error}</div>;
	}

	return (
		<div className='create-order-container'>
			<h2>Create Order</h2>

			<div className='order-layout'>
				<div className='products-section'>
					<h3>Available Products</h3>
					{products.length === 0 ? (
						<p>No products available</p>
					) : (
						<div className='product-list'>
							{products.map((product) => (
								<div
									key={product.id}
									className={`product-item ${!product.isActive ? 'inactive' : ''}`}
								>
									<div className='product-details'>
										<h4>{product.title || 'Untitled'}</h4>
										<p>{product.code}</p>
										{!product.isActive && <span className='inactive-badge'>Inactive</span>}
									</div>
									<button
										onClick={() => addProduct(product)}
										disabled={!product.isActive}
										className='add-button'
										title={!product.isActive ? 'Cannot add inactive product' : ''}
									>
										Add
									</button>
								</div>
							))}
						</div>
					)}
				</div>

				<div className='cart-section'>
					<h3>Order Items</h3>
					{orderItems.length === 0 ? (
						<p className='empty-cart'>No items in cart</p>
					) : (
						<>
							<div className='cart-items'>
								{orderItems.map((item) => {
									const product = products.find((p) => p.id === item.productId);
									return (
										<div
											key={item.productId}
											className='cart-item'
										>
											<div className='cart-item-info'>
												<strong>{product?.title || 'Product'}</strong>
												<span>{product?.code}</span>
											</div>
											<div className='cart-item-controls'>
												<input
													type='number'
													value={item.quantity}
													onChange={(e) => updateQuantity(item.productId, Number(e.target.value))}
													min='1'
													className='quantity-input'
												/>
												<button
													onClick={() => removeProduct(item.productId)}
													className='remove-button'
												>
													Remove
												</button>
											</div>
										</div>
									);
								})}
							</div>

							{/* Order Status Indicator */}
							{orderStatus !== 'idle' && (
								<div className={`order-status order-status-${orderStatus}`}>
									{orderStatus === 'creating' && (
										<>
											<span className='status-spinner'>⏳</span>
											<span>Creating order...</span>
										</>
									)}
									{orderStatus === 'processing' && (
										<>
											<span className='status-spinner'>🔄</span>
											<span>Processing order... Reserving inventory...</span>
										</>
									)}
									{orderStatus === 'confirmed' && (
										<>
											<span className='status-success'>✅</span>
											<span>Order confirmed! Redirecting...</span>
										</>
									)}
									{orderStatus === 'failed' && (
										<>
											<span className='status-error'>❌</span>
											<span>Order processing failed</span>
										</>
									)}
								</div>
							)}

							<button
								onClick={handleCreateOrder}
								className='create-order-button'
								disabled={orderStatus !== 'idle'}
							>
								{orderStatus === 'idle' ? 'Create Order' : 'Processing...'}
							</button>
						</>
					)}
				</div>
			</div>
		</div>
	);
};

export default CreateOrder;
