// frontend-react/src/components/Login/Login.tsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import './Login.css';

const Login: React.FC = () => {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [error, setError] = useState('');
	const [showRegisterModal, setShowRegisterModal] = useState(false);
	const [regEmail, setRegEmail] = useState('');
	const [regPassword, setRegPassword] = useState('');
	const [regError, setRegError] = useState('');
	const [regSuccess, setRegSuccess] = useState('');

	const { login, register } = useAuth();
	const navigate = useNavigate();

	const handleLogin = async (e: React.FormEvent) => {
		e.preventDefault();
		setError('');

		try {
			const response = await login({ email, password });
			if (response.isSuccess) {
				navigate('/products');
			} else {
				setError(response.message || 'Login failed');
			}
		} catch (err: unknown) {
			if (err && typeof err === 'object' && 'response' in err) {
				const axiosError = err as { response?: { data?: { message?: string } } };
				setError(axiosError.response?.data?.message || 'Error connecting to server');
			} else {
				setError('Error connecting to server');
			}
		}
	};

	const handleRegister = async (e: React.FormEvent) => {
		e.preventDefault();
		setRegError('');
		setRegSuccess('');

		if (!regEmail || !regPassword) {
			setRegError('Email and password are required');
			return;
		}

		if (regPassword.length < 8) {
			setRegError('Password must be at least 8 characters');
			return;
		}

		try {
			const response = await register({ email: regEmail, password: regPassword });
			if (response.isSuccess) {
				setRegSuccess('User registered successfully! You can now login.');
				setTimeout(() => {
					closeRegisterModal();
				}, 2000);
			} else {
				setRegError(response.message || 'Registration failed');
			}
		} catch (err: unknown) {
			let errorMsg = 'Error connecting to server';
			if (err && typeof err === 'object' && 'response' in err) {
				const axiosError = err as { response?: { data?: { message?: string } } };
				errorMsg = axiosError.response?.data?.message || 'Error connecting to server';
			}
			setRegError(errorMsg);
		}
	};

	const closeRegisterModal = () => {
		setShowRegisterModal(false);
		setRegEmail('');
		setRegPassword('');
		setRegError('');
		setRegSuccess('');
	};

	return (
		<div className='login-container'>
			<div className='login-box'>
				<h2>Login</h2>
				<form onSubmit={handleLogin}>
					<div className='form-group'>
						<label htmlFor='email'>Email</label>
						<input
							id='email'
							type='email'
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							required
							placeholder='Enter your email'
						/>
					</div>

					<div className='form-group'>
						<label htmlFor='password'>Password</label>
						<input
							id='password'
							type='password'
							value={password}
							onChange={(e) => setPassword(e.target.value)}
							required
							placeholder='Enter your password'
						/>
					</div>

					{error && <div className='error-message'>{error}</div>}

					<button
						type='submit'
						className='login-button'
					>
						Login
					</button>
				</form>

				<button
					type='button'
					className='register-button'
					onClick={() => setShowRegisterModal(true)}
				>
					Register
				</button>
			</div>

			{/* Register Modal */}
			{showRegisterModal && (
				<div
					className='modal-overlay'
					onClick={closeRegisterModal}
				>
					<div
						className='modal-content'
						onClick={(e) => e.stopPropagation()}
					>
						<div className='modal-header'>
							<h3>Create New User</h3>
							<button
								className='modal-close'
								onClick={closeRegisterModal}
							>
								×
							</button>
						</div>

						<form onSubmit={handleRegister}>
							<div className='form-group'>
								<label htmlFor='reg-email'>Email</label>
								<input
									id='reg-email'
									type='email'
									value={regEmail}
									onChange={(e) => setRegEmail(e.target.value)}
									required
									placeholder='Enter email'
								/>
							</div>

							<div className='form-group'>
								<label htmlFor='reg-password'>Password</label>
								<input
									id='reg-password'
									type='password'
									value={regPassword}
									onChange={(e) => setRegPassword(e.target.value)}
									required
									placeholder='Enter password (min 8 characters)'
								/>
							</div>

							{regError && <div className='error-message'>{regError}</div>}
							{regSuccess && <div className='success-message'>{regSuccess}</div>}

							<div className='modal-actions'>
								<button
									type='button'
									onClick={closeRegisterModal}
									className='cancel-button'
								>
									Cancel
								</button>
								<button
									type='submit'
									className='submit-button'
								>
									Create User
								</button>
							</div>
						</form>
					</div>
				</div>
			)}
		</div>
	);
};

export default Login;

// frontend/src/app/components/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  credentials = {
    email: '',
    password: '',
  };

  loading = false;
  error: string | null = null;

  // Register modal
  showRegisterModal = false;
  registerCredentials = {
    email: '',
    password: '',
  };
  registerLoading = false;
  registerError: string | null = null;
  registerSuccess = false;

  onSubmit() {
    this.loading = true;
    this.error = null;

    this.authService.login(this.credentials).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.router.navigate(['/products']);
        }
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Invalid credentials. Please try again.';
        console.error('Login error:', err);
        this.loading = false;
      },
    });
  }

  openRegisterModal() {
    this.showRegisterModal = true;
    this.registerCredentials = { email: '', password: '' };
    this.registerError = null;
    this.registerSuccess = false;
  }

  closeRegisterModal() {
    this.showRegisterModal = false;
    this.registerCredentials = { email: '', password: '' };
    this.registerError = null;
    this.registerSuccess = false;
  }

  onRegister() {
    this.registerLoading = true;
    this.registerError = null;

    this.authService.register(this.registerCredentials).subscribe({
      next: (response) => {
        if (response.isSuccess) {
          this.registerSuccess = true;
          this.registerLoading = false;

          // Auto-close modal after 2 seconds and optionally auto-login
          setTimeout(() => {
            this.closeRegisterModal();
            // Optionally, you can auto-login the user
            // this.credentials = { ...this.registerCredentials };
            // this.onSubmit();
          }, 2000);
        }
        this.registerLoading = false;
      },
      error: (err) => {
        console.error('Register error:', err);
        // Check for specific error messages from backend
        if (err.error?.message) {
          this.registerError = err.error.message;
        } else if (err.status === 409) {
          this.registerError =
            'This email is already registered. Please use a different email.';
        } else if (err.status === 400) {
          this.registerError =
            'Invalid email or password format. Please check your input.';
        } else {
          this.registerError = 'Registration failed. Please try again.';
        }
        this.registerLoading = false;
      },
    });
  }
}

<div class="login-container">
  <div class="login-card">
    <h2>Login to E-Commerce</h2>

    <form (ngSubmit)="onSubmit()" #loginForm="ngForm">
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="email"
          id="email"
          name="email"
          [(ngModel)]="credentials.email"
          required
          email
          placeholder="admin@admin.com"
          class="form-input"
        />
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          [(ngModel)]="credentials.password"
          required
          placeholder="12345678"
          class="form-input"
        />
      </div>

      <div *ngIf="error" class="error-message">
        {{ error }}
      </div>

      <button
        type="submit"
        class="btn-login"
        [disabled]="!loginForm.valid || loading"
      >
        {{ loading ? 'Logging in...' : 'Login' }}
      </button>

      <button type="button" class="btn-register" (click)="openRegisterModal()">
        Register
      </button>
    </form>

    <div class="hint-box">
      <p><strong>Test Credentials:</strong></p>
      <p>Email: <code>admin&#64;admin.com</code></p>
      <p>Password: <code>12345678</code></p>
      <p class="note">Make sure the backend seeder has been run.</p>
    </div>
  </div>

  <!-- Register Modal -->
  <div
    class="modal-overlay"
    *ngIf="showRegisterModal"
    (click)="closeRegisterModal()"
  >
    <div class="register-modal" (click)="$event.stopPropagation()">
      <h3>Create New Account</h3>

      <form (ngSubmit)="onRegister()" #registerForm="ngForm">
        <div class="form-group">
          <label for="registerEmail">Email</label>
          <input
            type="email"
            id="registerEmail"
            name="registerEmail"
            [(ngModel)]="registerCredentials.email"
            required
            email
            placeholder="your.email@example.com"
            class="form-input"
          />
        </div>

        <div class="form-group">
          <label for="registerPassword">Password</label>
          <input
            type="password"
            id="registerPassword"
            name="registerPassword"
            [(ngModel)]="registerCredentials.password"
            required
            minlength="8"
            placeholder="Minimum 8 characters"
            class="form-input"
          />
        </div>

        <div *ngIf="registerError" class="error-message">
          {{ registerError }}
        </div>

        <div *ngIf="registerSuccess" class="success-message">
          ✓ Account created successfully!
        </div>

        <div class="modal-buttons">
          <button
            type="button"
            class="btn-cancel"
            (click)="closeRegisterModal()"
            [disabled]="registerLoading"
          >
            Cancel
          </button>
          <button
            type="submit"
            class="btn-confirm"
            [disabled]="
              !registerForm.valid || registerLoading || registerSuccess
            "
          >
            {{ registerLoading ? 'Creating...' : 'Create Account' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
